# Generated by Django 2.2.3 on 2019-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='wish',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
