# Generated by Django 2.2.3 on 2019-07-22 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlog',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
